### ISSUE TITLE
is number bool value

### ISSUE THREAD

**Issue by danco8** [insightindustry/validator-collection#42] opened 2019-10-19 13:38 UTC
checkers.is_numeric(True) return True
This is bug because the value is bool,
may i make a PR for this subject?

**Comment by insightindustry** [comment] 2019-10-19 15:48
Thanks, but this is actually not a bug, as in Python the `bool` type technically is a numeric type that inherits from `int`, such that `True == 1` and `False == 0`.

In Python 2.x you can reassign the identity of `True` or `False` to something non-numeric, but that will still be evaluated appropriately in the checker. In Python 3+ they are instead language keywords which cannot be reassigned, so they are always numeric.

Here are links to the Python PEPs and standard library documentation associated with booleans: 

https://docs.python.org/2.3/whatsnew/section-bool.html

https://www.python.org/dev/peps/pep-0285/

https://docs.python.org/3/library/stdtypes.html

And here’s a link to a very thorough explanation on StackOverflow: https://stackoverflow.com/questions/2764017/is-false-0-and-true-1-in-python-an-implementation-detail-or-is-it-guarante

**Closed** 2019-10-19 15:49 UTC
Labels: wontfix
