### ISSUE TITLE
URL checker does not support private IPs

### ISSUE THREAD

**Issue by fschoenm** [insightindustry/validator-collection#29] opened 2019-03-19 12:43 UTC
The following URL check fails even though it should be correct:

    is_url('http://127.0.0.1:8443/index.html', allow_special_ips=True)

When using a public IP (e.g. 1.1.1.1), it seems to work.

**Comment by insightindustry** [comment] 2019-03-19 19:49
This is caused by the same root problem as #28 . Will be fixed in v. 1.3.3.

**Comment by insightindustry** [comment] 2019-03-23 20:01
Closed in v.1.3.3 by #30

**Closed by insightindustry** 2019-03-23 20:01 UTC
Labels: duplicate
