### ISSUE TITLE
Checkers.isURL not recognising locahost

### ISSUE THREAD

**Issue by matthewsnell** [insightindustry/validator-collection#23] opened 2018-12-21 20:03 UTC
`checkers.is_url("http://localhost)` returns False as does `checkers.is_url("127.0.0.1")`

**Comment by insightindustry** [comment] 2018-12-22 03:36
There's actually several issues here:
* There is a bug where special-use domain names (e.g. ``localhost``, ``invalid``, ``test``, and ``example``) are not correctly identified as special-use domain name (see [RFC 6761](https://tools.ietf.org/html/rfc6761) ) when validating against domain names.
* There is a bug where special-use domain names are not correctly identified as valid domain names when validating URLs.
* By design, the ``checkers.is_url()`` and ``validators.url()`` functions do *not* recognize specific IP addresses (localhost, loopback, etc.) as being valid URLs because they are considered to be special cases per the relevant RFCs. I'll be adding a property labeled ``allow_special_ips`` to the ``validators.url()`` and ``checkers.is_url()`` functions that will detect them, however.

These three issues will be addressed in release **1.3.2**.

**Comment by matthewsnell** [comment] 2018-12-22 14:55
Great, thank you very much

**Closed** 2019-02-09 18:35 UTC
Labels: bug
